CREATE OR REPLACE TRIGGER trg_limit_comment_length
BEFORE INSERT ON HOZZASZOLAS
FOR EACH ROW
BEGIN
    IF LENGTH(:NEW.TARTALOM) > 500 THEN
        :NEW.TARTALOM := SUBSTR(:NEW.TARTALOM, 1, 500);
END IF;
END;
/
